---
login: "YOUR_USERNAME"
password: "YOUR_PASSWORD"

debug: 0
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"

tag_list: ["synthesizer", 
"musicproducing", 
"producingmusic", 
"makingmusic", 
"musicart", 
"festivals", 
"musicfestival",
"bassmusic",
"dancemusic",
"electronicdancemusic",
"nerd",
"edm",
"producers",
"artist",
"basshouse",
"dubstep",
"futurebass",
"dancemusic",
"musicbusiness",
"musicmaking",
"bassmusic",
"musicstudio"
"electronica",
"indiemusic",
"techno",
"ableton",
"cubase",
"flstudio"
]


tag_blacklist: ["sex", 
"porno", 
"free", 
"travel", 
"shop", 
"store", 
"online", 
"f4f", 
"buy", 
"sell",
"instagram"

]

like_per_day: 196
max_like_for_one_tag: 36
media_min_like: 20
media_max_like: 200
like_followers_per_run: 0

unlike_per_day: 0
time_till_unlike: 259200

follow_per_day: 0
follow_time: 259200
follow_attempts: 10
user_min_follow: 125
user_max_follow: 2000

unfollow_per_day: 0
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: true
unfollow_inactive: true
unfollow_recent_feed: false
unfollow_whitelist: [""]

unwanted_username_list: ["free", "travel", "shop", "store", "sex", "online", "f4f", "sell", "follow", "follower", "sad", "stupid"]
comments_per_day: 196
comment_list: [
        ["ğŸ‘ŒğŸ»", "ğŸ‘ğŸ»", "âœŒğŸ»", 
        "ğŸ’•", 
        "ğŸ˜ğŸ˜", 
        "ğŸ™ˆğŸ™ˆ", 
        "ğŸ‘ğŸ»", 
        "ğŸ˜…", 
        "ğŸ˜‡", 
        "ğŸ™ƒ", 
        "ğŸ˜‰", 
        "ğŸ¤“",
        "ğŸ˜", 
        "ğŸ¤©", 
        "ğŸ˜º", 
        "âœŠğŸ»", 
        "ğŸ¤ŸğŸ»", 
        "ğŸµ",
        "ğŸ¦„"]
    ]
